# This file contains test experiment settings

model_name: "vit_large_patch14_clip_quickgelu_224.openai"
fast_settings: True
dataset: "New-Generator_COCO17_unbiased"
batch_size: 8
profiler: False

# jepa score calc settings
vectorize: False
score_type: "last_layer_spectral"