model_name: "vit_large_patch14_clip_224.openai"
fast_settings: false
dataset: "Imagenet_val_5k"
batch_size: 8
profiler: False

vectorize: False
score_type: "last_layer"    # produces JSONL with embeddings (for the kNN bank)

cal_set_path: null
k_neighbors: null
