# This file contains test experiment settings

model_name: "vit_base_patch16_clip_quickgelu_224.metaclip_400m"
fast_settings: False
dataset: "ForenSynths"
batch_size: 32
profiler: False

# jepa score calc settings
vectorize: False
score_type: "local_last_layer"

cal_set_path: "/home/tischuet/zero-shot-deepfake-detection/outputs/vit_base_patch16_clip_quickgelu_224_metaclip_400m/vit_base_patch16_clip_quickgelu_224_metaclip_400m_last_layer_Imagenet_val_5k.jsonl"        # not used for this run
k_neighbors: 100         # not used for this run