model_name: "vit_base_patch32_clip_quickgelu_224.metaclip_400m"
fast_settings: false
dataset: "Imagenet_val_5k"
batch_size: 32
profiler: False

vectorize: False
score_type: "last_layer"    # produces JSONL with embeddings (for the kNN bank)

cal_set_path: null
k_neighbors: null
