# This file contains test experiment settings

model_name: "vit_base_patch16_clip_quickgelu_224.metaclip_400m"
fast_settings: True
dataset: "Imagenet_val_5k"
batch_size: 1
profiler: False

# jepa score calc settings
vectorize: False
score_type: "layerwise"
layers: [6, 7, 12]