# This file contains test experiment settings

model_name: "vit_large_patch14_clip_quickgelu_224.metaclip_400m"
fast_settings: True
dataset: "ForenSynths_rest"
batch_size: 1
profiler: False

# jepa score calc settings
vectorize: False
score_type: "layerwise_fast"
layers: [10, 15, 16, 24]
chunk_size: 128